### ISSUE TITLE
No Smelting/Blasting Recipes for Pigsteel Chunk -> Iron Nugget

### ISSUE THREAD

**Issue by VoidLeech** [Uraneptus/Pigsteel-forge-1.16#7]
**Version**
5.0.0

**Problem**
No recipes exist to smelt pigsteel chunks

**Expected behaviour**
A recipe exists (the changelog says it should)

**Comment by Uraneptus** [comment]
Oooppss 😅
Gonna fix both problems you mentioned later, not gonna comment on both tho.
Thanks for reporting this!
